### ISSUE TITLE
Openshift Yaml

### ISSUE THREAD

**Issue by emalpb** [brotandgames/ciao#52]
Yaml file for Openshift
It is a yaml file for RedHat Openshift which you can add to your repository to be used.

```

apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: ciao
    name: ciao
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentconfig: ciao
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 10
    labels:
      app: ciao
    name: ciao
  spec:
    replicas: 1
    selector:
      app: ciao
      deploymentconfig: ciao
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: ciao
          deploymentconfig: ciao
      spec:
        containers:
        - env:
          - name: PORT
            value: "3000"
          - name: SMTP_ADDRES
            value: smtp.blabla.com
          - name: SMTP_EMAIL_FROM
            value: dasda@dasda.com.ar
          - name: SMTP_EMAIL_TO
            value: dasda@dasda.com.ar
          - name: CIAO_WEBHOOK_ENDPOINT_OFFICE_365
            value: https://outlook.office.com/webhook/changehere
          - name: CIAO_WEBHOOK_PAYLOAD_OFFICE_365
            value: 'payload'
          image: brotandgames/ciao
          imagePullPolicy: Always
          name: ciao
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /app/db/sqlite
            name: ciao-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ciao-1
          persistentVolumeClaim:
            claimName: ciao
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ciao
        from:
          kind: ImageStreamTag
          name: ciao:latest
          namespace: CURRENT_NAMESPACE
        lastTriggeredImage: brotandgames/ciao
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2019-09-05T14:51:40Z
    creationTimestamp: null
    generation: 2
    labels:
      app: ciao
    name: ciao
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: brotandgames/ciao
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/CURRENT_NAMESPACE/ciao:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""

```
