### ISSUE TITLE
[helm] Fix liveness and readiness probes

### ISSUE THREAD

**Issue by bykvaadm** [brotandgames/ciao#62]
**Describe the bug**
U shoud add some variables to values.yaml, so we can manage liveness adnd readiness probes:

1. deployment.yaml

```
          livenessProbe:
            httpGet:
              path: /
              port: http
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values..livenessProbe.successThreshold }}

... repeat for readiness ...
```

2.  set defaults in values.yaml

```
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 4
  timeoutSeconds: 10
... repeat for readiness ...
```
