### ISSUE TITLE
remove quotes in placeholders

### ISSUE THREAD

**Issue by HAndy2013** [brotandgames/ciao#65]
Hi, ^_^
I'm using docker-compose, and here is my yml file
````
version: "3"
services:
  ciao:
    image: brotandgames/ciao
    container_name: ciao
    ports:
      - '8300:3000'
    environment:
      [...]
      - CIAO_WEBHOOK_PAYLOAD_MONITOR={ "status_before":"__status_before__", "status_after":"__status_after__"}
      - CIAO_WEBHOOK_ENDPOINT_MONITOR=http://host.com/xxx
````

my webhook will parse request payload to json object, but [__status_before__] and [__status_after__]  will contains quotes when my web-proxy is shutting down , for example: "Failed to open TCP connection to 200.1.3.19:8200 (Connection refused - connect(2) for "200.1.3.19" port 8200)", and this causes parsing failed.
